
auth.token=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

defaults.org=bo-been-koh
defaults.project=fireballing

defaults.url=https://sentry.io/
