/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./lib/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#8c39fb',
        'primary-light': '#f5edff',
        'on-primary': '#ffffff',
        background: '#ffffff',
        surface: '#f5f5f5',
        'surface-dim': '#e3e3e3',
        'on-surface': '#1a1a1a',
        'on-surface-variant': '#888888',
        outline: '#e3e3e3',
        'outline-variant': '#bfbfbf',
        'text-primary': '#1a1a1a',
        'text-secondary': '#1b1b1b',
        'text-tertiary': '#40403f',
        'text-muted': '#888888',
        'text-placeholder': '#bfbfbf',
        'text-disabled': '#e3e3e3',
        error: '#ff1744',
        'on-error': '#ffffff',
        info: '#2979ff',
      },
      fontFamily: {
        heading: ['Pretendard', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Pretendard', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '110%', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '120%', fontWeight: '700' }],
        h3: ['20px', { lineHeight: '130%', fontWeight: '600' }],
        subtitle: ['16px', { lineHeight: '140%', fontWeight: '700', letterSpacing: '-0.01em' }],
        body: ['16px', { lineHeight: '140%', fontWeight: '500', letterSpacing: '-0.01em' }],
        'body-sm': ['14px', { lineHeight: '140%', fontWeight: '500', letterSpacing: '-0.01em' }],
        detail: ['14px', { lineHeight: '140%', fontWeight: '600', letterSpacing: '-0.01em' }],
        caption: ['12px', { lineHeight: '100%', fontWeight: '400', letterSpacing: '-0.01em' }],
        'label-md': ['14px', { lineHeight: '140%', fontWeight: '600', letterSpacing: '-0.01em' }],
        'label-sm': ['12px', { lineHeight: '120%', fontWeight: '500', letterSpacing: '-0.01em' }],
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '8px',
        pill: '10px',
        md: '12px',
        lg: '16px',
        xl: '20px',
      },
      spacing: {
        xs: '4px',
        '1.5': '6px',
        sm: '8px',
        '2.5': '10px',
        '3': '12px',
        '3.5': '14px',
        md: '16px',
        gutter: '20px',
        lg: '24px',
        '7': '28px',
        xl: '32px',
        '2xl': '48px',
      },
    },
  },
  plugins: [],
};
